#:schema node_modules/wrangler/config-schema.json
name = "svelte-onlinettt"
compatibility_date = "2024-05-15"
pages_build_output_dir = "dist"

[env.development]
kv_namespaces = [
    { binding = "TTT_GAME_KV", id = "2ed8441b10cd4ca59cfeaa3081b4b7d1" }
]

[env.production]
kv_namespaces = [
    { binding = "TTT_GAME_KV", id = "da8a29a1985a49de9be56c5d41188229" }
]

# Uncomment when we add WebSocket support
# [[durable_objects.bindings]]
# name = "WEBSOCKET_HIBERNATION_SERVER"
# class_name = "WebSocketHibernationServer"