#:schema node_modules/wrangler/config-schema.json
name = "svelte-online-ttt"
compatibility_date = "2024-05-15"
pages_build_output_dir = "dist"

# Add nodejs compatibility for SvelteKit
compatibility_flags = ["nodejs_compat"]

[env.preview]
kv_namespaces = [
    { binding = "TTT_GAME_KV", id = "2ed8441b10cd4ca59cfeaa3081b4b7d1" }
]

# Add services to preview environment (using production WebSocket worker)
[[env.preview.durable_objects]]
binding = "WEBSOCKET_HIBERNATION_SERVER"
name = "WebSocketHibernationServer"
script_name = "svelte-ttt-websocket"

[env.production]
kv_namespaces = [
    { binding = "TTT_GAME_KV", id = "da8a29a1985a49de9be56c5d41188229" }
]

# FIXED: Change from services to durable_objects
[[env.production.durable_objects]]
binding = "WEBSOCKET_HIBERNATION_SERVER"
name = "WebSocketHibernationServer"
script_name = "svelte-ttt-websocket"