name = "svelte-ttt-websocket"
main = "src/index.ts"
compatibility_date = "2024-05-15"

[durable_objects]
bindings = [
    { name = "WEBSOCKET_HIBERNATION_SERVER", class_name = "WebSocketHibernationServer" }
]

# For free plan, use new_sqlite_classes instead of new_classes
[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketHibernationServer"]