name = "svelte-ttt-websocket"
main = "src/index.ts"
compatibility_date = "2024-05-15"
compatibility_flags = ["nodejs_compat"]

# Enable ES Module format (required for Durable Objects)
[build]
command = ""

# Durable Objects configuration
[[durable_objects.bindings]]
name = "WEBSOCKET_HIBERNATION_SERVER"
class_name = "WebSocketHibernationServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketHibernationServer"]

# When running locally use `wrangler dev --local --port 8787`

